/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  VestingVaultBase,
  VestingVaultBaseInterface,
} from "../VestingVaultBase";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "beneficiary",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "VaultBeneficiaryUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "enum VestingVaultMeta.Status",
        name: "newStatus",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "enum VestingVaultMeta.Status",
        name: "prevStatus",
        type: "uint8",
      },
    ],
    name: "VaultStatusUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "VaultTokenChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256[]",
        name: "unlockingTimes",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "percents",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "precision",
        type: "uint256",
      },
    ],
    name: "VaultVestingInfoChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "beneficiary",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "VaultWithdraw",
    type: "event",
  },
  {
    inputs: [],
    name: "getAllBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllBeneficiaries",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "beneficiary",
        type: "address",
      },
    ],
    name: "getBeneficiary",
    outputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bool[]",
        name: "isPortionWithdraw",
        type: "bool[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getStatus",
    outputs: [
      {
        internalType: "enum VestingVaultMeta.Status",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getToken",
    outputs: [
      {
        internalType: "contract IERC20",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getVestingInfo",
    outputs: [
      {
        internalType: "uint256[]",
        name: "vestingPortionsUnlockTime",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "vestingPercentPerPortion",
        type: "uint256[]",
      },
      {
        internalType: "uint256",
        name: "vestingPercentPrecision",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getZeroDate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class VestingVaultBase__factory {
  static readonly abi = _abi;
  static createInterface(): VestingVaultBaseInterface {
    return new utils.Interface(_abi) as VestingVaultBaseInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): VestingVaultBase {
    return new Contract(address, _abi, signerOrProvider) as VestingVaultBase;
  }
}
